# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20170815_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classlist',
            options={'verbose_name': '班级信息表', 'verbose_name_plural': '班级信息表'},
        ),
    ]
