# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20170816_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程信息表', 'verbose_name_plural': '课程信息表'},
        ),
        migrations.AlterModelOptions(
            name='courserecord',
            options={'verbose_name': '上课记录表', 'verbose_name_plural': '上课记录表'},
        ),
    ]
