# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20170816_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classlist',
            old_name='course',
            new_name='name',
        ),
    ]
