# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20170816_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserecord',
            name='day_number',
            field=models.PositiveIntegerField(help_text='此处填写第几节课或第几天课程...,必须为数字', verbose_name='节次'),
        ),
    ]
