# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20170817_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserecord',
            name='class_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ClassList', verbose_name='班级(课程)'),
        ),
        migrations.AlterUniqueTogether(
            name='classlist',
            unique_together=set([('course', 'semester')]),
        ),
    ]
