# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20170817_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('crm_app_index', '可以查看freeadmin所有的app首页'), ('crm_table_list', '可以查看freeadmin表里的所有数据'), ('crm_table_list_view', '可以查看freeadmin表里每条数据的修改页'), ('crm_table_list_change', '可以修改freeadmin表里每条数据'))},
        ),
    ]
