# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20170823_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
