# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20170824_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='contract_agreed',
            field=models.BooleanField(default=False, help_text='我已认真阅读', verbose_name='学员已签署协议'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='contract_approved',
            field=models.BooleanField(default=False, help_text='销售审核', verbose_name='协议已审核'),
        ),
    ]
