# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_auto_20170824_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
